### ISSUE TITLE
Automatic refresh not ran on zsh on initial use

### ISSUE THREAD

**Issue by DougVonMoser** [carsdotcom/bitcar#4]
the cache is not refreshed automatically on initial use as the readme describes. 

I have only installed on zsh, but a manual run of bit --refresh is required.

**Comment by machellerogden** [comment]
Are you on the latest version? 1.6.0? I will try to replicate. Thanks for the report.

**Comment by machellerogden** [comment]
@DougVonMoser I wasn't able to replicate. Cache initialized as expected on first search attempt while using zsh.

![pasted_image_3_20_17__9_09_am](https://cloud.githubusercontent.com/assets/237323/24103425/36e3b092-0d4d-11e7-85d4-91dd1746d589.png)

**Comment by machellerogden** [comment]
@DougVonMoser any luck?

**Comment by DougVonMoser** [comment]
Yup! good now. Must not have had the latest.
